apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: mssql-persistent
  labels:
    app: mssql
spec:
  storageClassName: thin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
