kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mssql-persistent-scc
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- '*'
users:
- system:admin
- system:serviceaccount:mssql-persistent:mssql-persistent-sa
